import = [
	"~/.config/alacritty/catppuccin-frappe.toml"
	# "~/.config/alacritty/catppuccin-macchiato.toml"
	# "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
# option_as_alt = "OnlyLeft" # macOS only

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"
